---
- hosts: all
  become: true
  become_user: root
  pre_tasks:
    - name: Apply all available updates in RedHat
      yum:
        name: '*'
        state: latest
      tags: [update,skip-this]

### Ref - https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
    - name: Reboot the server
      command: /sbin/shutdown -r now "Rebooted after updating through ansible"
      async: 0
      poll: 0
      become: true
      ignore_errors: true
      tags: [reboot,skip-this]

    - name: Waiting for server to come back after reboot
      local_action: wait_for host="{{ inventory_hostname }}" state=started delay=30 timeout=300
      become: false
      tags: [reboot,skip-this]
  roles:
    - rh6xtocentos6x
