---

    - name: Write a new file for swapfile
      command: dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size }} creates={{ swapfile_location }}
      register: write_swapfile
      tags: [install,xe]

    - name: Set swapfile permissions
      file: path={{ swapfile_location }} mode=0600
      tags: [install,xe]

    - name: Create swapfile
      command: mkswap {{ swapfile_location }}
      register: create_swapfile
      tags: [install,xe]

    - name: Enable swapfile
      command: swapon {{ swapfile_location }}
      when: create_swapfile.changed
      tags: [install,xe]

    - name: Add swapfile to /etc/fstab
      lineinfile: dest=/etc/fstab line="{{ swapfile_location }}   none    swap    sw    0   0" state=present
      tags: [install,xe]
