# handlers file for apex-upgrade
- name: Restart httpd
  service:
    name: httpd
    state: restarted
  when: (APACHE_FRONT == "yes")

- name: Restart tomcat
  service:
    name: tomcat
    state: restarted
